services:
  mongo:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - test_task_mongodb:/data/db
    container_name: python_db_test_task
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - test_task-network

  bot:
    build: .
    command: python main.py
    volumes:
      - ./:/code/
    networks:
      - test_task-network
    depends_on:
      mongo:
        condition: service_healthy

    container_name: python-test_task

volumes:
  test_task_mongodb:

networks:
  test_task-network:
